// <auto-generated />
using System;
using ElarabyCA.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ElarabyCA.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("ElarabyCA.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("OID");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Birthdate")
                        .HasColumnType("datetime");

                    b.Property<bool?>("ChangePasswordOnFirstLogon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateEnrolled")
                        .HasColumnType("datetime");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Gcrecord")
                        .HasColumnType("INTEGER")
                        .HasColumnName("GCRecord");

                    b.Property<string>("IdentityNumber")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsTechnician")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ObjectType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OptimisticLockField")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryPhone")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryPhone")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredPassword")
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Town")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Oid")
                        .HasName("OID");

                    b.HasIndex("Gcrecord")
                        .HasDatabaseName("iGCRecord_Employee");

                    b.HasIndex("ObjectType")
                        .HasDatabaseName("iObjectType_Employee");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.FinancialTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Amount")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModified")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Type")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("TransactionId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Type");

                    b.ToTable("FinancialTransaction");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentBalance")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModified")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<int>("OpeningBalance")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SparePartId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InventoryId");

                    b.HasIndex("SparePartId");

                    b.HasIndex("StoreId");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.InventoryTransaction", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Amount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("InventoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModified")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenceId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReferenceType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("TransactionId");

                    b.HasIndex("InventoryId");

                    b.HasIndex("Type");

                    b.ToTable("InventoryTransaction");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("OID");

                    b.Property<int?>("ActiveTicket")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("CaseNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Complaint")
                        .HasColumnType("TEXT");

                    b.Property<string>("Customer")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateAssigned")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateLastDelayed")
                        .HasColumnType("datetime");

                    b.Property<int?>("Gcrecord")
                        .HasColumnType("INTEGER")
                        .HasColumnName("GCRecord");

                    b.Property<int?>("InterfaceStatus")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsArgent")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsSynchronized")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("OptimisticLockField")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Orderid")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("ORDERID");

                    b.Property<string>("OverviewNotes")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryPhone")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Product")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReasonLastDelayed")
                        .HasColumnType("TEXT");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReportsOverview")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RowBytesCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Sapnumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SAPNumber");

                    b.Property<string>("SecondaryPhone")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SiteIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Street")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Town")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WorkOrderId")
                        .HasColumnType("TEXT");

                    b.HasKey("Oid");

                    b.HasIndex("ActiveTicket")
                        .HasDatabaseName("iActiveTicket_Order");

                    b.HasIndex("Gcrecord")
                        .HasDatabaseName("iGCRecord_Order");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.OrderSMSMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSent")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Report")
                        .HasColumnType("TEXT");

                    b.Property<int>("SMSMessageId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SendCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("SMSMessageId");

                    b.ToTable("OrderSMSMessage");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.OrderTicket", b =>
                {
                    b.Property<int>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("OID");

                    b.Property<int?>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("CauseUnCompletion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime");

                    b.Property<int?>("Employee")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Gcrecord")
                        .HasColumnType("INTEGER")
                        .HasColumnName("GCRecord");

                    b.Property<bool?>("IncludeInOrderNotes")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Notable")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OptimisticLockField")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Report")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Oid");

                    b.HasIndex("Category")
                        .HasDatabaseName("iCategory_OrderTicket");

                    b.HasIndex("Employee")
                        .HasDatabaseName("iEmployee_OrderTicket");

                    b.HasIndex("Gcrecord")
                        .HasDatabaseName("iGCRecord_OrderTicket");

                    b.HasIndex("Order")
                        .HasDatabaseName("iOrder_OrderTicket");

                    b.ToTable("OrderTicket");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.SMSMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SMSMessage");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.SparePart", b =>
                {
                    b.Property<int>("SparePartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Barcode")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("SparePartId");

                    b.HasIndex("Category");

                    b.ToTable("SparePart");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.Store", b =>
                {
                    b.Property<int>("StoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Administrator")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("StoreId");

                    b.HasIndex("Administrator");

                    b.ToTable("Store");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.TicketCategory", b =>
                {
                    b.Property<int>("Oid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("OID");

                    b.Property<bool?>("Activatable")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AllowDuplicates")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BackColor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FontColor")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FontStyle")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Gcrecord")
                        .HasColumnType("INTEGER")
                        .HasColumnName("GCRecord");

                    b.Property<bool?>("IncludeInOrderNotes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OptimisticLockField")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Reportable")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("SupportApplyInBatches")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Oid");

                    b.HasIndex("Gcrecord")
                        .HasDatabaseName("iGCRecord_TicketCategory");

                    b.HasIndex("Title")
                        .IsUnique()
                        .HasDatabaseName("iTitle_TicketCategory");

                    b.ToTable("TicketCategory");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.ValueGroup", b =>
                {
                    b.Property<int>("ValueGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("Group")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastModified")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.HasKey("ValueGroupId");

                    b.ToTable("ValueGroup");
                });

            modelBuilder.Entity("ElarabyCA.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.DeviceFlowCodes", b =>
                {
                    b.Property<string>("UserCode")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DeviceCode")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Expiration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("UserCode");

                    b.HasIndex("DeviceCode")
                        .IsUnique();

                    b.HasIndex("Expiration");

                    b.ToTable("DeviceCodes");
                });

            modelBuilder.Entity("IdentityServer4.EntityFramework.Entities.PersistedGrant", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("Expiration")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubjectId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.HasIndex("Expiration");

                    b.HasIndex("SubjectId", "ClientId", "Type");

                    b.ToTable("PersistedGrants");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.FinancialTransaction", b =>
                {
                    b.HasOne("ElarabyCA.Domain.Entities.Employee", "EmployeeNavigation")
                        .WithMany("FinancialTransactions")
                        .HasForeignKey("EmployeeId")
                        .HasConstraintName("FK_FinancialTransaction_Employee");

                    b.HasOne("ElarabyCA.Domain.Entities.ValueGroup", "TypeNavigation")
                        .WithMany("FinancialTransactionTypes")
                        .HasForeignKey("Type")
                        .HasConstraintName("FK_FinancialTransaction_ValueObject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeNavigation");

                    b.Navigation("TypeNavigation");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.Inventory", b =>
                {
                    b.HasOne("ElarabyCA.Domain.Entities.SparePart", "SparePart")
                        .WithMany("Inventories")
                        .HasForeignKey("SparePartId")
                        .HasConstraintName("FK_Inventory_SparePart")
                        .IsRequired();

                    b.HasOne("ElarabyCA.Domain.Entities.Store", "Store")
                        .WithMany("Inventories")
                        .HasForeignKey("StoreId")
                        .HasConstraintName("FK_Inventory_Store")
                        .IsRequired();

                    b.Navigation("SparePart");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.InventoryTransaction", b =>
                {
                    b.HasOne("ElarabyCA.Domain.Entities.Inventory", "Inventory")
                        .WithMany("InventoryTransactions")
                        .HasForeignKey("InventoryId")
                        .HasConstraintName("FK_InventoryTransaction_Inventory")
                        .IsRequired();

                    b.HasOne("ElarabyCA.Domain.Entities.ValueGroup", "TypeNavigation")
                        .WithMany("InventoryTransactionTypes")
                        .HasForeignKey("Type")
                        .HasConstraintName("FK_InventoryTransaction_ValueObject");

                    b.Navigation("Inventory");

                    b.Navigation("TypeNavigation");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.Order", b =>
                {
                    b.HasOne("ElarabyCA.Domain.Entities.OrderTicket", "ActiveTicketNavigation")
                        .WithMany("OrderNavigation")
                        .HasForeignKey("ActiveTicket")
                        .HasConstraintName("FK_Order_ActiveTicket");

                    b.Navigation("ActiveTicketNavigation");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.OrderSMSMessage", b =>
                {
                    b.HasOne("ElarabyCA.Domain.Entities.Order", "Order")
                        .WithMany("OrderSMSMessages")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElarabyCA.Domain.Entities.SMSMessage", "SMSMessage")
                        .WithMany("OrderSMSMessages")
                        .HasForeignKey("SMSMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("SMSMessage");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.OrderTicket", b =>
                {
                    b.HasOne("ElarabyCA.Domain.Entities.TicketCategory", "CategoryNavigation")
                        .WithMany("OrderTicket")
                        .HasForeignKey("Category")
                        .HasConstraintName("FK_OrderTicket_Category");

                    b.HasOne("ElarabyCA.Domain.Entities.Employee", "EmployeeNavigation")
                        .WithMany("OrderTicket")
                        .HasForeignKey("Employee")
                        .HasConstraintName("FK_OrderTicket_Employee");

                    b.HasOne("ElarabyCA.Domain.Entities.Order", "Order1")
                        .WithMany("OrderTicket")
                        .HasForeignKey("Order")
                        .HasConstraintName("FK_OrderTicket_Order");

                    b.Navigation("CategoryNavigation");

                    b.Navigation("EmployeeNavigation");

                    b.Navigation("Order1");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.SparePart", b =>
                {
                    b.HasOne("ElarabyCA.Domain.Entities.ValueGroup", "CategoryNavigation")
                        .WithMany("SparePartCategories")
                        .HasForeignKey("Category")
                        .HasConstraintName("FK_SparePart_ValueObject");

                    b.Navigation("CategoryNavigation");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.Store", b =>
                {
                    b.HasOne("ElarabyCA.Domain.Entities.Employee", "AdministratorNavigation")
                        .WithMany("Stores")
                        .HasForeignKey("Administrator")
                        .HasConstraintName("FK_Store_Employee")
                        .IsRequired();

                    b.Navigation("AdministratorNavigation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ElarabyCA.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ElarabyCA.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ElarabyCA.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ElarabyCA.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.Employee", b =>
                {
                    b.Navigation("FinancialTransactions");

                    b.Navigation("OrderTicket");

                    b.Navigation("Stores");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.Inventory", b =>
                {
                    b.Navigation("InventoryTransactions");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderSMSMessages");

                    b.Navigation("OrderTicket");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.OrderTicket", b =>
                {
                    b.Navigation("OrderNavigation");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.SMSMessage", b =>
                {
                    b.Navigation("OrderSMSMessages");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.SparePart", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.Store", b =>
                {
                    b.Navigation("Inventories");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.TicketCategory", b =>
                {
                    b.Navigation("OrderTicket");
                });

            modelBuilder.Entity("ElarabyCA.Domain.Entities.ValueGroup", b =>
                {
                    b.Navigation("FinancialTransactionTypes");

                    b.Navigation("InventoryTransactionTypes");

                    b.Navigation("SparePartCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
